In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('superstore.csv')

In [3]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [4]:
df['Product.Name'].value_counts()

Product.Name
Staples                                                                      227
Cardinal Index Tab, Clear                                                     92
Eldon File Cart, Single Width                                                 90
Rogers File Cart, Single Width                                                84
Ibico Index Tab, Clear                                                        83
                                                                            ...
Zebra GK420t Direct Thermal/Thermal Transfer Printer                           1
Xerox 1918                                                                     1
Plantronics Single Ear Headset                                                 1
Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order      1
Socket Bluetooth Cordless Hand Scanner (CHS)                                   1
Name: count, Length: 3788, dtype: int64

In [5]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [7]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['Category'].value_counts()

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [10]:
pd.crosstab(df['Segment'],df['Category'])

Category     Furniture  Office Supplies  Technology
Segment
Consumer          5095            16151        5272
Corporate         3014             9364        3051
Home Office       1767             5758        1818

In [11]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [12]:

df['City'].value_counts()

City
New York City            915
Los Angeles              747
Philadelphia             537
San Francisco            510
Santo Domingo            443
                        ...
Hadera                     1
Morley                     1
Villeneuve-la-Garenne      1
Torremolinos               1
Redwood City               1
Name: count, Length: 3636, dtype: int64

In [13]:
df['Country'].value_counts()

Country
United States    9994
Australia        2837
France           2827
Mexico           2644
Germany          2065
                 ...
South Sudan         2
Chad                2
Swaziland           2
Eritrea             2
Bahrain             2
Name: count, Length: 147, dtype: int64

In [14]:
df['Customer.ID'].value_counts()

Customer.ID
JG-158051    40
WB-218504    37
BC-111252    37
AF-108701    36
JG-158052    35
             ..
DK-33752      1
AA-3752       1
TG-113102     1
TB-115951     1
AO-108104     1
Name: count, Length: 4873, dtype: int64

In [15]:
df = df.drop('Customer.Name',axis=1)

In [16]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Discount', 'Market',
       '记录数', 'Order.Date', 'Order.ID', 'Order.Priority', 'Product.ID',
       'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID', 'Sales',
       'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [17]:
df['Discount'].value_counts()

Discount
0.000    29009
0.200     4998
0.100     4068
0.400     3177
0.600     2006
0.700     1786
0.500     1633
0.170      735
0.470      725
0.150      541
0.002      461
0.270      388
0.300      340
0.450      327
0.800      316
0.250      198
0.070      150
0.350      122
0.402      104
0.370       74
0.202       41
0.320       27
0.602       23
0.650       17
0.570       12
0.550       10
0.850        2
Name: count, dtype: int64

In [18]:
df['Market'].value_counts()

Market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

| Market Value | Meaning                         |
| ------------ | ------------------------------- |
| APAC         | Asia-Pacific                    |
| EU           | Europe                          |
| US           | United States                   |
| LATAM        | Latin America                   |
| EMEA         | Europe, Middle East, and Africa |
| Africa       | African countries               |
| Canada       | Canada                          |

In [19]:
df = df.drop('记录数',axis=1)

In [20]:
df['Order.Date'].value_counts()

Order.Date
2014-06-18 00:00:00.000    135
2014-11-18 00:00:00.000    127
2014-09-03 00:00:00.000    126
2014-11-20 00:00:00.000    118
2014-12-29 00:00:00.000    116
                          ...
2012-03-11 00:00:00.000      1
2013-01-06 00:00:00.000      1
2011-01-16 00:00:00.000      1
2013-07-21 00:00:00.000      1
2011-02-13 00:00:00.000      1
Name: count, Length: 1430, dtype: int64

In [21]:
df['Order.Date'] = pd.to_datetime(df['Order.Date'])

In [22]:
df['Month'] = df['Order.Date'].dt.month
df['Year'] = df['Order.Date'].dt.year

In [23]:
df.head()

,Category,City,Country,Customer.ID,Discount,Market,Order.Date,Order.ID,Order.Priority,Product.ID,...,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum,Month
0,Office Supplies,Los Angeles,United States,LS-172304,0.0,US,2011-01-07,CA-2011-130813,High,OFF-PA-10002005,...,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2,1
1,Office Supplies,Los Angeles,United States,MV-174854,0.0,US,2011-01-21,CA-2011-148614,Medium,OFF-PA-10002893,...,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4,1
2,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,2011-08-05,CA-2011-118962,Medium,OFF-PA-10000659,...,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32,8
3,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,2011-08-05,CA-2011-118962,Medium,OFF-PA-10001144,...,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32,8
4,Office Supplies,Los Angeles,United States,AP-109154,0.0,US,2011-09-29,CA-2011-146969,High,OFF-PA-10002105,...,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40,9

In [24]:
df = df.drop('Order.Date',axis=1)

In [25]:
df = df.drop('Order.ID',axis=1)

In [26]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Discount', 'Market',
       'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity',
       'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode',
       'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum',
       'Month'],
      dtype='object')

In [27]:
df['Order.Priority'].value_counts()

Order.Priority
Medium      29433
High        15501
Critical     3932
Low          2424
Name: count, dtype: int64

In [28]:
df.rename(columns={'Order.Priority':'Order_priority','Customer.ID':'Customer_id','Product.Name':'Product_name','Shipping.Cost':'Shipping_cost','Sub.Category':'Sub_category','Ship.Date':'Ship_date','Ship.Mode':'Ship_mode'}, inplace= True)

In [29]:
df = df.drop('Product.ID',axis=1)

In [30]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Row.ID', 'Sales', 'Segment', 'Ship_date', 'Ship_mode', 'Shipping_cost',
       'State', 'Sub_category', 'Year', 'Market2', 'weeknum', 'Month'],
      dtype='object')

In [31]:
df['Profit'].value_counts()

Profit
0.0000      668
4.3200       70
3.9600       69
7.9200       67
2.6400       63
           ...
152.6760      1
75.7280       1
223.5480      1
118.8320      1
3.1584        1
Name: count, Length: 24575, dtype: int64

In [32]:
df['Quantity'].value_counts()

Quantity
2     12748
3      9682
1      8963
4      6385
5      4882
6      3020
7      2385
8      1361
9       987
10      276
14      186
12      176
11      156
13       83
Name: count, dtype: int64

In [33]:
df['Region'].value_counts()

Region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

In [34]:
df = df.drop('Row.ID',axis=1)

In [35]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Sales', 'Segment', 'Ship_date', 'Ship_mode', 'Shipping_cost', 'State',
       'Sub_category', 'Year', 'Market2', 'weeknum', 'Month'],
      dtype='object')

In [36]:
df['Segment'].value_counts()

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [37]:
df = df.drop('Ship_date',axis=1)

In [38]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Sales', 'Segment', 'Ship_mode', 'Shipping_cost', 'State',
       'Sub_category', 'Year', 'Market2', 'weeknum', 'Month'],
      dtype='object')

In [39]:
df['Shipping_cost'].value_counts()

Shipping_cost
1.360      66
0.350      66
0.710      63
1.040      63
0.640      63
           ..
28.570      1
16.846      1
154.610     1
11.139      1
173.000     1
Name: count, Length: 16877, dtype: int64

In [40]:
df['State'].value_counts()

State
California       2001
England          1499
New York         1128
Texas             985
Ile-de-France     981
                 ...
Yevrey              1
Vrancea             1
Stara Zagora        1
Paysandú            1
Wyoming             1
Name: count, Length: 1094, dtype: int64

In [41]:
df['Sub_category'].value_counts()

Sub_category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [42]:
df = df.drop(columns={'Market2'},axis=1)

In [43]:
df['weeknum'].value_counts()

weeknum
47    1527
46    1524
45    1508
52    1461
38    1453
48    1441
49    1440
39    1426
51    1381
50    1378
36    1358
37    1350
24    1337
26    1281
25    1228
33    1188
34    1166
23    1153
32    1147
35    1119
40    1118
44    1053
43    1046
42    1017
41     940
19     936
22     891
31     856
27     837
20     821
21     812
53     763
12     745
16     742
28     728
15     724
30     720
17     714
14     711
11     697
18     692
10     679
29     664
13     649
3      604
7      592
5      568
4      568
2      550
9      543
8      536
6      527
1      381
Name: count, dtype: int64

In [44]:
df.head()

,Category,City,Country,Customer_id,Discount,Market,Order_priority,Product_name,Profit,Quantity,Region,Sales,Segment,Ship_mode,Shipping_cost,State,Sub_category,Year,weeknum,Month
0,Office Supplies,Los Angeles,United States,LS-172304,0.0,US,High,Xerox 225,9.3312,3,West,19,Consumer,Second Class,4.37,California,Paper,2011,2,1
1,Office Supplies,Los Angeles,United States,MV-174854,0.0,US,Medium,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,19,Consumer,Standard Class,0.94,California,Paper,2011,4,1
2,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,Medium,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,21,Consumer,Standard Class,1.81,California,Paper,2011,32,8
3,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,Medium,Xerox 1913,53.2608,2,West,111,Consumer,Standard Class,4.59,California,Paper,2011,32,8
4,Office Supplies,Los Angeles,United States,AP-109154,0.0,US,High,Xerox 223,3.1104,1,West,6,Consumer,Standard Class,1.32,California,Paper,2011,40,9

In [45]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Sales', 'Segment', 'Ship_mode', 'Shipping_cost', 'State',
       'Sub_category', 'Year', 'weeknum', 'Month'],
      dtype='object')

In [46]:
pd.crosstab(df['Region'],df['Shipping_cost'].mean())

col_0           26.375818
Region
Africa               4587
Canada                384
Caribbean            1690
Central             11117
Central Asia         2048
EMEA                 5029
East                 2848
North                4785
North Asia           2338
Oceania              3487
South                6645
Southeast Asia       3129
West                 3203

In [47]:
pd.crosstab(df['State'],df['Category'])

Category  Furniture  Office Supplies  Technology
State
'Ajman            0                3           1
'Amman            7               26           7
'Asir             2                5           1
Abia              4               18           3
Abruzzi           5               12           1
...             ...              ...         ...
Zinder            0                3           1
Zulia             7               24           5
Zürich            3               24           7
Šiauliai          1                3           0
Žilina            0                2           0

[1094 rows x 3 columns]

In [48]:
df['State'] = df['State'].str.replace("'", "", regex=True)

In [49]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Sales', 'Segment', 'Ship_mode', 'Shipping_cost', 'State',
       'Sub_category', 'Year', 'weeknum', 'Month'],
      dtype='object')

In [50]:
# Sales ≠ Profit Analysis
df.groupby('Sub_category')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)

                Sales        Profit
Sub_category
Phones        1706874  216717.00580
Copiers       1509439  258567.54818
Chairs        1501682  140396.26750
Bookcases     1466559  161924.41950
Storage       1127124  108461.48980
Appliances    1011081  141680.58940
Machines       779071   58867.87300
Tables         757034  -64083.38870
Accessories    749307  129626.30620
Binders        461952   72449.84600
Furnishings    385609   46967.42550
Art            372163   57953.91090
Paper          244307   59207.68270
Supplies       243090   22583.26310
Envelopes      170926   29601.11630
Fasteners       83254   11525.42410
Labels          73433   15010.51200

In [51]:
# Sales ≠ Profit Analysis
df.groupby('Sub_category')[['Sales','Profit']].sum().sort_values(by='Profit',ascending=False)

                Sales        Profit
Sub_category
Copiers       1509439  258567.54818
Phones        1706874  216717.00580
Bookcases     1466559  161924.41950
Appliances    1011081  141680.58940
Chairs        1501682  140396.26750
Accessories    749307  129626.30620
Storage       1127124  108461.48980
Binders        461952   72449.84600
Paper          244307   59207.68270
Machines       779071   58867.87300
Art            372163   57953.91090
Furnishings    385609   46967.42550
Envelopes      170926   29601.11630
Supplies       243090   22583.26310
Labels          73433   15010.51200
Fasteners       83254   11525.42410
Tables         757034  -64083.38870

- Phone have highest sales and 2nd highest profit 
- Copies have 2nd highest in sales and highest in profit 
- We have to mainly focuss on Phone, Copies, Bookcases, Appliances, Chair and Storage

In [52]:
df.groupby('Sub_category')['Discount'].mean().sort_values(ascending=True)

Sub_category
Paper          0.109469
Copiers        0.117147
Art            0.117362
Labels         0.120449
Accessories    0.120481
Supplies       0.127918
Envelopes      0.131749
Storage        0.138464
Fasteners      0.140595
Appliances     0.141709
Phones         0.145847
Furnishings    0.151066
Bookcases      0.153758
Chairs         0.163110
Machines       0.169583
Binders        0.179207
Tables         0.290732
Name: Discount, dtype: float64

- Copies have low discount

In [53]:
df.groupby('Discount')[['Sales','Profit']].mean().sort_values(by='Profit',ascending=False)

               Sales       Profit
Discount
0.070     810.800000   140.990022
0.002     567.017354   125.762649
0.100     388.303343    63.683426
0.000     241.053949    61.039514
0.150     565.687616    50.602409
0.170     336.604082    38.317107
0.200     240.867347    23.552594
0.250     444.762626     4.043371
0.270     230.286082    -4.317213
0.202     395.439024   -14.518847
0.450     102.131498   -41.610973
0.470     115.078621   -42.982420
0.400     176.127479   -45.246603
0.300     555.626471   -57.899557
0.370     427.229730   -78.462191
0.600      92.016949   -81.732147
0.320     536.703704   -88.560656
0.500     198.496632   -97.140158
0.700      78.258679  -104.339576
0.402     324.394231  -109.908138
0.350     784.459016  -116.144693
0.800      64.753165  -122.203244
0.602     216.391304  -213.279085
0.550     630.800000  -315.067200
0.650     387.058824  -365.997971
0.570     678.666667  -526.129000
0.850     398.500000 -1534.329000

- 25%+ Discount give loss 
- 40%+ Discount give high loss

In [54]:
df.groupby('Customer_id')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)

             Sales     Profit
Customer_id
SM-203204    25042 -1980.7393
TC-209804    19050  8981.3239
CS-118451    16655  2995.5816
SP-209202    16566  4974.5130
VG-218051    15654  2748.1878
...            ...        ...
LP-70951         4     0.4200
LH-70202         4    -2.7480
BS-17552         3    -2.7240
CK-22051         3    -3.2580
AH-1202          2    -3.3780

[4873 rows x 2 columns]

In [55]:
df.head()

,Category,City,Country,Customer_id,Discount,Market,Order_priority,Product_name,Profit,Quantity,Region,Sales,Segment,Ship_mode,Shipping_cost,State,Sub_category,Year,weeknum,Month
0,Office Supplies,Los Angeles,United States,LS-172304,0.0,US,High,Xerox 225,9.3312,3,West,19,Consumer,Second Class,4.37,California,Paper,2011,2,1
1,Office Supplies,Los Angeles,United States,MV-174854,0.0,US,Medium,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,19,Consumer,Standard Class,0.94,California,Paper,2011,4,1
2,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,Medium,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,21,Consumer,Standard Class,1.81,California,Paper,2011,32,8
3,Office Supplies,Los Angeles,United States,CS-121304,0.0,US,Medium,Xerox 1913,53.2608,2,West,111,Consumer,Standard Class,4.59,California,Paper,2011,32,8
4,Office Supplies,Los Angeles,United States,AP-109154,0.0,US,High,Xerox 223,3.1104,1,West,6,Consumer,Standard Class,1.32,California,Paper,2011,40,9

In [56]:
customer_sales = df.groupby('Customer_id')['Sales'].sum()

persentage = (customer_sales / customer_sales.sum()) * 100

persentage.sort_values(ascending = False)

Customer_id
SM-203204    0.198072
TC-209804    0.150677
CS-118451    0.131734
SP-209202    0.131030
VG-218051    0.123816
               ...
LP-70951     0.000032
LH-70202     0.000032
BS-17552     0.000024
CK-22051     0.000024
AH-1202      0.000016
Name: Sales, Length: 4873, dtype: float64

In [57]:
df.groupby('Month')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)

         Sales        Profit
Month
12     1580816  170718.12710
11     1551319  175449.48412
9      1437432  170438.18316
8      1293852  151854.10972
6      1269751  147079.41684
10     1168220  157269.35838
5       904061  104509.78428
3       770519   94087.52096
7       749423   78070.09172
4       698603   73513.63124
1       675141   73535.38454
2       543768   70932.19922

- December and November has the hoghest sales and even Highest Profit also

In [58]:
df[['Sales','Profit','Discount']].corr()

             Sales    Profit  Discount
Sales     1.000000  0.484923 -0.086728
Profit    0.484923  1.000000 -0.316490
Discount -0.086728 -0.316490  1.000000

- Discounts did not significantly improve sales performance, indicating that aggressive discount strategies may not effectively increase revenue
- Increasing discounts tends to reduce profit margins, suggesting that excessive discounting negatively impacts business profitability.
- Higher sales generally lead to higher profit, but the relationship is not very strong, indicating that some high-sales products may still generate low profit.

In [59]:
df.groupby(['Category','Month'])[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)

                        Sales       Profit
Category        Month
Technology      11     579668  83526.07712
                12     572530  74941.03690
Furniture       12     538930  35002.85550
Technology      9      515802  60509.81016
Furniture       11     502727  31599.98780
Technology      8      498080  70788.53992
Furniture       9      494667  48544.24020
Technology      6      485689  72813.86904
                10     485156  82111.86308
Office Supplies 12     469356  60774.23470
                11     468924  60323.41920
                9      426963  61384.13280
Furniture       6      411255  29258.40310
Office Supplies 8      402560  60443.51650
Furniture       8      393212  20622.05330
                10     382260  32620.04510
Office Supplies 6      372807  45007.14470
Technology      5      343526  52047.75278
Office Supplies 10     300804  42537.45020
Technology      3      287922  39598.73476
                7      287352  32301.98812
Furniture       5      280693  13120.79950
Office Supplies 5      279842  39341.23200
Technology      4      259762  35000.21174
Furniture       3      254898  18728.97950
Office Supplies 7      234963  31613.50870
Furniture       1      228560  14173.71760
Office Supplies 3      227699  35759.80670
                4      227634  28672.73400
Furniture       7      227108  14154.59490
Technology      1      224330  28484.29364
Office Supplies 1      222251  30877.37330
Furniture       4      211207   9840.68550
Technology      2      204874  31654.55592
Furniture       2      185367  17538.36180
Office Supplies 2      153527  21739.28150

- Technolgy has highest sale among all in 11th and 12th month
- Feburary is the month where sales hits the most

In [60]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_id', 'Discount', 'Market',
       'Order_priority', 'Product_name', 'Profit', 'Quantity', 'Region',
       'Sales', 'Segment', 'Ship_mode', 'Shipping_cost', 'State',
       'Sub_category', 'Year', 'weeknum', 'Month'],
      dtype='object')

In [61]:
df.groupby('Ship_mode')[['Sales','Profit']].mean()

                     Sales     Profit
Ship_mode
First Class     243.979614  27.728804
Same Day        247.020363  28.201802
Second Class    248.884179  28.381368
Standard Class  246.267717  28.938945

In [62]:
df.groupby('City')[['Sales','Profit']].sum()

                       Sales    Profit
City
Aachen                  3804  1116.981
Aalen                    980   283.005
Aalst                    388   152.310
Aba                     1063 -1475.556
Abadan                  1355   233.820
...                      ...       ...
Zwedru                    49    11.850
Zwickau                   98    19.380
Zwolle                   151   -55.095
eMbalenhle                76    13.620
Águas Lindas de Goiás    186    41.040

[3636 rows x 2 columns]

- City Aba has high tax

In [63]:
df.to_csv('clean_superstore.csv', index=False)

In [65]:
df['Sales'].sum()

np.int64(12642905)